

from io import BytesIO
from typing import Optional

from fastapi import Depends,APIRouter,File, Form,UploadFile,HTTPException
from sqlalchemy.ext.asyncio import AsyncSession 
from sqlalchemy import select
import models
from database import get_db
import schemas
import shutil
from storage import delete_file, upload_image,upload_audio,upload_desc_audio
from dotenv import load_dotenv
import os
import requests

import json

from gtts import gTTS


load_dotenv()


router = APIRouter(prefix='/user',tags=['user'])

#  fetch all animals from database
@router.get('/all_animals',response_model=list[schemas.AllAnimalResponse])
async def all_animals(db:AsyncSession=Depends(get_db)):
    result = await  db.execute(
         select(models.Animal)
    )
 
    animals = result.scalars().all()
    return animals




# get with specise option  ( name , image, id)
@router.get('/animals_by_species/{species}',response_model=list[schemas.AllAnimalResponse])
async def animals_by_species(species:str,db:AsyncSession=Depends(get_db)):
        result = await db.execute(
             select(models.Animal).where(models.Animal.species==species)
        )
        animal = result.scalars().all()
        return animal



       

# get the specific animal from the database when long pressed on the animal card in the frontend
@router.get('/animal/{id}',response_model=schemas.AllAnimalResponse)
async def get_animal(id:int, db:AsyncSession=Depends(get_db)):
    result = await db.execute(
         select(models.Animal).where(models.Animal.id == id)
    )
    animal = result.scalars().first()
    return animal



# for the single click
@router.get('/animal_audio/{id}',response_model=schemas.AudioResponse)
async def get_Animal_Audio(id:int,db:AsyncSession=Depends(get_db)):
     result = await db.execute(
          select(models.Animal).where(models.Animal.id==id)
     )
     animal_audio = result.scalars().first()
     return animal_audio


# send request to admin
@router.post('/animal/send_request/{animal_id}',response_model=schemas.AnimalRequestResponse)
async def animal_request(animal_id:int,db:AsyncSession=Depends(get_db)):

    result = await db.execute(
        select(models.AigeneratedAnimal).where(models.AigeneratedAnimal.id == animal_id)
    )

    # print('result',result)

    
        
    animal = result.scalars().first()

    if not animal:
            raise HTTPException(status_code=404, detail="Animal not found")

    

    # add request to request databse
    new_request = models.AnimalRequests(
        name = animal.name,
        species = animal.species,
        description = animal.description,
        desc_audio_url = animal.desc_audio_url,
        image_url = animal.image_url,
        audio_url = animal.audio_url,
        status = 'pending'
    )
 
    db.add(new_request)
    await db.commit()
    await db.refresh(new_request)

    await db.delete(animal)   # delete the ai animal from the database 
    await db.commit()
    

    return new_request 


# cacle the request or don't like the animal generated by ai
@router.post('/animal/cancel_request/{animal_id}')
async def cancel_animal_request(animal_id:int,db:AsyncSession=Depends(get_db)):

    result = await db.execute(
        select(models.AigeneratedAnimal).where(models.AigeneratedAnimal.id==animal_id)
    )

    animal = result.scalars().first()

    if not animal:
        raise HTTPException(status_code=404, detail="Animal request not found")
    

    # delete the files from the storage
    delete_file("animal-image", animal.image_url)
    delete_file("animal-audio", animal.audio_url)
    delete_file("desc-audio", animal.desc_audio_url)


    # delete the animal from the ai generated table
    await db.delete(animal)
    await db.commit()
    return {"message" : "request cancelled successfully"}



# ------------------------------------------------------ ai section ------------------------------------------------





# cloudflare 
CF_API_TOKEN = os.getenv('CF_API_TOKEN')
CF_ACC_ID = os.getenv('CF_ACC_ID')



 
# ai generated animal
@router.post('/generate_ai_animal')   # response_model=schemas.AllAnimalResponse
async def generate_ai_animal(name:str,style: str,audio_file: UploadFile = File(...),db:AsyncSession=Depends(get_db)):    


    # --------------------checking in the db ----------------------------------
    result = await db.execute(
        select(models.Animal).where(models.Animal.name==name)
    )

    existing_animal = result.scalars().first()

    if existing_animal:
        return existing_animal
    


    # ---------------------generating Decsription with ai model ----------------------------------


    # method - 1 using hugging face and open ai


    # print(TEXT_MODEL)

    # client = OpenAI(
    #     base_url="https://router.huggingface.co/v1",
    #     api_key=HF_TOKEN,
    # )

    #     response = client.chat.completions.create(
    #         model=TEXT_MODEL,
    #         messages=[
    #             {
    #                 "role": "user",
    #                 "content": f"Describe a {name} in simple words for kids and need only response nothing else like sure and yes etc"
    #         }
    #     ],
    #     max_tokens=100
    # )

        
    #     desc = response.choices[0].message.content



    # method -2 : using the cloudfare ai model

    text_url = f"https://api.cloudflare.com/client/v4/accounts/{CF_ACC_ID}/ai/run/@cf/meta/llama-3-8b-instruct"


    prompt : f"""
        You are an AI that classifies animals for kids.

        Return ONLY valid JSON.

        Rules:
        - "type" must be one of: pet, wild, bird, sea, insect
        - "description" must be 1–2 simple lines for children
        - Do NOT include scientific names
        - Keep language very simple

        Animal: {name}

        Format:
        {{
        "name": "",
        "type": "",
        "description": ""
        }}
        """

    text_payload = {
        "messages" : [
            {
                "role":"user",
                "content":f"""
        You are an AI that classifies animals for kids.

        Return ONLY valid JSON.

        Rules:
        - "type" must be one of: pet, wild, bird, sea, farm, insect
        - "description" must be 3-4 simple sentences for children
        - Do NOT include scientific names
        - Keep language very simple

        Animal: {name}

        Format:
        {{
        "name": "",
        "type": "",
        "description": ""
        }}
        """
            }
        ]
    }

    headers = {

    'Authorization': f"Bearer {CF_API_TOKEN}",
    "Content-Type": "application/json"
    }


    text_response = requests.post(text_url,headers=headers,json=text_payload)

    if text_response.status_code !=200:
        return {"error" : text_response.text}

    raw = text_response.json()['result']['response']

    desc = json.loads(raw)    # to acces name,type,description use desc['name'],desc['type'],desc['description']

    
    # print(raw['name']) 
    # print(raw['type']) 
    # print(raw['description']) 
    # return desc


    # --------------------------- generating Images with ai ------------------------------------------------

   
    
    


    # now using the cloudfare ai cause it is alternative workarounds

    img_url = f"https://api.cloudflare.com/client/v4/accounts/{CF_ACC_ID}/ai/run/@cf/stabilityai/stable-diffusion-xl-base-1.0"



    # here need to make the chnages
    if style == "2d":
         img_payload = {
        "prompt": f"A single {name} illustrated as a realistic animal. The animal should be centered and shown alone (no other animals). Use bright, clean, and minimal colors while keeping the natural, realistic color palette and body shape of a real {name}. Style should be simple, soft with smooth outlines. Plain or very minimal background, no text, no extra objects."
        }
         
    elif style == "3d":
         img_payload = {
        "prompt": f"""
        A cute 3D cartoon {name} for kids.

        Requirements:
        - Single animal only
        - Pixar-style 3D render
        - Colorful but minimal
        - Match realistic animal shape and natural colors
        - Kid-friendly
        - Soft lighting
        - High-quality 3D look
        - Clean background
        """
        }


    img_response = requests.post(img_url,headers=headers,json=img_payload)


    if img_response.status_code != 200:
        return {"error": img_response.text}
    


    #----------------------------------- audio generation -------------------------------------------------------------


    # audio = generate_animal_sound(data.name)



    # # Save image
    # with open(f"static/images/{name}.png", "wb") as f:
    #     f.write(img_response.content)

    # # manual audio save 
    # with open(f"static/audio/{name}.mp3", "wb") as buffer:
    #     shutil.copyfileobj(audio_file.file, buffer)



    supabase_image_url = upload_image(
    img_response.content,
    f"{name}.png"
)

    audio_bytes = await audio_file.read()

    supabase_audio_url = upload_audio(
        audio_bytes,
        f"{name}.mp3"
    )



    # generate the description audio using gtts

    tts = gTTS(text=desc['description'], lang='en')

    audio_buffer = BytesIO()
    tts.write_to_fp(audio_buffer)

    audio_buffer.seek(0)

    supabase_desc_audio_url = upload_desc_audio(
        file_bytes=audio_buffer.read(),
        filename=f"{name}.mp3",
        
    )

    
    # save to the datbase
    ai_generated_animal = models.AigeneratedAnimal(
        name=desc['name'].capitalize(),
        species=desc['type'].capitalize(),
        description=desc['description'],
        desc_audio_url=supabase_desc_audio_url,
        image_url=supabase_image_url,
        audio_url=supabase_audio_url
    )

    db.add(ai_generated_animal)
    await db.commit()
    await db.refresh(ai_generated_animal)
    return ai_generated_animal      




@router.patch('/edit_ai_animal/{animal_id}')
async def edit_ai_animal(
    animal_id: int,

    # optional text fields
    name: Optional[str] = None,
    species: Optional[str] = None,
    description: Optional[str] = None,

    # optional file uploads
    image_file: Optional[UploadFile] = File(None),
    audio_file: Optional[UploadFile] = File(None),

    db: AsyncSession = Depends(get_db)
    ):
    # Check animal exists
    result = await db.execute(
        select(models.AigeneratedAnimal).where(
            models.AigeneratedAnimal.id == animal_id
        )
    )

    animal = result.scalars().first()

    if not animal:
        raise HTTPException(status_code=404, detail="Animal not found")

     # Update only if value actually provided
    if name:
        animal.name = name.strip().capitalize()

    if species and species.strip():
        animal.species = species.strip().capitalize()

    if description and description.strip():
        animal.description = description.strip()

    

    # Optional image upload
    if image_file and image_file.filename:
        
        if animal.image_url:
            delete_file("animal-image", animal.image_url)


        image_bytes = await image_file.read()

        image_url = upload_image(
            file_bytes=image_bytes,
            filename=f"{animal.name}.png",
        
        )

        animal.image_url = image_url

    # Optional audio upload
    if audio_file and audio_file.filename:
        
        if animal.audio_url:
            delete_file("animal-audio", animal.audio_url)

        audio_bytes = await audio_file.read()
        audio_path = upload_audio(
            file_bytes=audio_bytes,
            filename=f"{animal.name}.mp3",
        )

        animal.audio_url = audio_path

    # Regenerate description audio only if description changed
    if description:
        
        if animal.desc_audio_url:
            delete_file("desc-audio", animal.desc_audio_url)

        


        tts = gTTS(description, lang='en')
        audio_buffer = BytesIO()
        tts.write_to_fp(audio_buffer)

        audio_buffer.seek(0)

        desc_audio_path = upload_desc_audio(
            file_bytes=audio_buffer.read(),
            filename=f"{animal.name}.wav",
        )

        animal.desc_audio_url = desc_audio_path

    await db.commit()
    await db.refresh(animal)

    return animal




 